branch-defaults:
  master:
    environment: dev
    group_suffix: null
global:
  application_name: studies-octo-adventure-pm
  default_ec2_keyname: null
  default_platform: Docker 1.9.1
  default_region: us-west-2
  profile: eb-cli
  sc: git
